name: verify iupp promotion
on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: '0 13 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go env
        uses: actions/setup-go@v3.3.0
      - name: iupp promo verification
        uses: GabrielBB/xvfb-action@v1
        with:
          run: go run ${{github.workspace}}/main.go
        env:
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
          SENDGRID_SENDER_EMAIL: ${{ secrets.SENDGRID_SENDER_EMAIL }}
          SENDGRID_TO_EMAIL: ${{ secrets.SENDGRID_TO_EMAIL }}
          SENDGRID_TO_NAME: ${{ secrets.SENDGRID_TO_NAME }} 
        run:  echo ${#SENDGRID_SENDER_EMAIL}
      - name: commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: update last check
             
