name: Run Python Test
on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go environment
        uses: actions/setup-go@v3.3.0
      - name: Iupp lastest promotions verification
        uses: GabrielBB/xvfb-action@v1
        with:
          run: go run ${{github.workspace}}/main.go
