name: verify iupp promotion
on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go environment
        uses: actions/setup-go@v3.3.0
      - name: Iupp lastest promotions verification
        uses: GabrielBB/xvfb-action@v1
        env:
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
          SENDGRID_SENDER_EMAIL: ${{ secrets.SENDGRID_SENDER_EMAIL }}
          SENDGRID_TO_EMAIL: ${{ secrets.SENDGRID_TO_EMAIL }}
          SENDGRID_TO_NAME: ${{ secrets.SENDGRID_TO_NAME }}
        with:
          run: go run ${{github.workspace}}/main.go
